name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["feature"]
assignees:
  - klacol
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create this feature request. We all develop in our free time, so there is no guarantee that I can work on your request.
  - type: textarea
    id: related-to-problem
    attributes:
      label: Related to a problem?
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].
    validations:
      required: false
  - type: textarea
    id: possible-solution
    attributes:
      label: Describe the solution you'd like
      description: Please describe.
      placeholder:  clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Please describe.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Please describe.
      placeholder: Add any other context or screenshots about the feature request here.
    validations:
      required: false

